# Generated by Django 2.2.1 on 2020-06-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='profile_pic_url',
        ),
    ]
