# Generated by Django 3.0.5 on 2020-07-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fb_post_clean_arch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('pub_date_time', models.DateTimeField(auto_now=True)),
                ('post_content', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reaction_type', models.CharField(choices=[('LIKE', 'LIKE'), ('WOW', 'WOW'), ('HAHA', 'HAHA'), ('DISLIKE', 'DISLIKE'), ('SAD', 'SAD'), ('ANGRY', 'ANGRY')], default=None, max_length=10, null=True)),
                ('comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_post_clean_arch.Comment')),
                ('post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_post_clean_arch.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=250)),
                ('pub_date_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('parent_comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='fb_post_clean_arch_v2.Comment')),
                ('post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='fb_post_clean_arch.Post')),
            ],
        ),
    ]
