# Generated by Django 2.2.1 on 2020-06-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=250)),
                ('pub_date_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('parent_comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fb_post_clean_arch.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('pub_date_time', models.DateTimeField(auto_now=True)),
                ('post_content', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reaction_type', models.CharField(choices=[('LIKE', 'LIKE'), ('WOW', 'WOW'), ('HAHA', 'HAHA'), ('DISLIKE', 'DISLIKE'), ('SAD', 'SAD'), ('ANGRY', 'ANGRY')], default=None, max_length=10, null=True)),
                ('comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='fb_post_clean_arch.Comment')),
                ('post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='fb_post_clean_arch.Post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fb_post_clean_arch.Post'),
        ),
    ]
